percent_party <- function(data_set){
  return(round(prop.table(table(data_set$PARTYID)),3))
}

party_analysis <- function(data_set,target_year){
  x <- year(drop_na(data_set,PARTYID),target_year)
  dem <-c(percent_party(straight(x))["1"],
          percent_party(lgbt(x))["1"],
          percent_party(men(straight(x)))["1"],
          percent_party(men(lgbt(x)))["1"],
          percent_party(women(straight(x)))["1"],
          percent_party(women(lgbt(x)))["1"],
          percent_party(white(straight(x)))["1"],
          percent_party(white(lgbt(x)))["1"],
          percent_party(poc(straight(x)))["1"],
          percent_party(poc(lgbt(x)))["1"],
          percent_party(white(men((straight(x)))))["1"],
          percent_party(white(men(lgbt(x))))["1"],
          percent_party(poc(men(straight(x))))["1"],
          percent_party(poc(men(lgbt(x))))["1"],
          percent_party(white(women(straight(x))))["1"],
          percent_party(white(women(lgbt(x))))["1"],
          percent_party(poc(women(straight(x))))["1"],
          percent_party(poc(women(lgbt(x))))["1"])
  rep <- c(percent_party(straight(x))["2"],
           percent_party(lgbt(x))["2"],
           percent_party(men(straight(x)))["2"],
           percent_party(men(lgbt(x)))["2"],
           percent_party(women(straight(x)))["2"],
           percent_party(women(lgbt(x)))["2"],
           percent_party(white(straight(x)))["2"],
           percent_party(white(lgbt(x)))["2"],
           percent_party(poc(straight(x)))["2"],
           percent_party(poc(lgbt(x)))["2"],
           percent_party(white(men((straight(x)))))["2"],
           percent_party(white(men(lgbt(x))))["2"],
           percent_party(poc(men(straight(x))))["2"],
           percent_party(poc(men(lgbt(x))))["2"],
           percent_party(white(women(straight(x))))["2"],
           percent_party(white(women(lgbt(x))))["2"],
           percent_party(poc(women(straight(x))))["2"],
           percent_party(poc(women(lgbt(x))))["2"])
  ind <- c(percent_party(straight(x))["3"],
           percent_party(lgbt(x))["3"],
           percent_party(men(straight(x)))["3"],
           percent_party(men(lgbt(x)))["3"],
           percent_party(women(straight(x)))["3"],
           percent_party(women(lgbt(x)))["3"],
           percent_party(white(straight(x)))["3"],
           percent_party(white(lgbt(x)))["3"],
           percent_party(poc(straight(x)))["3"],
           percent_party(poc(lgbt(x)))["3"],
           percent_party(white(men((straight(x)))))["3"],
           percent_party(white(men(lgbt(x))))["3"],
           percent_party(poc(men(straight(x))))["3"],
           percent_party(poc(men(lgbt(x))))["3"],
           percent_party(white(women(straight(x))))["3"],
           percent_party(white(women(lgbt(x))))["3"],
           percent_party(poc(women(straight(x))))["3"],
           percent_party(poc(women(lgbt(x))))["3"])
  oth <- c(percent_party(straight(x))["4"],
           percent_party(lgbt(x))["4"],
           percent_party(men(straight(x)))["4"],
           percent_party(men(lgbt(x)))["4"],
           percent_party(women(straight(x)))["4"],
           percent_party(women(lgbt(x)))["4"],
           percent_party(white(straight(x)))["4"],
           percent_party(white(lgbt(x)))["4"],
           percent_party(poc(straight(x)))["4"],
           percent_party(poc(lgbt(x)))["4"],
           percent_party(white(men((straight(x)))))["4"],
           percent_party(white(men(lgbt(x))))["4"],
           percent_party(poc(men(straight(x))))["4"],
           percent_party(poc(men(lgbt(x))))["4"],
           percent_party(white(women(straight(x))))["4"],
           percent_party(white(women(lgbt(x))))["4"],
           percent_party(poc(women(straight(x))))["4"],
           percent_party(poc(women(lgbt(x))))["4"])
  obs <- c(nrow(straight(x)),
           nrow(lgbt(x)),
           nrow(men(straight(x))),
           nrow(men(lgbt(x))),
           nrow(women(straight(x))),
           nrow(women(lgbt(x))),
           nrow(white(straight(x))),
           nrow(white(lgbt(x))),
           nrow(poc(straight(x))),
           nrow(poc(lgbt(x))),
           nrow(white(men((straight(x))))),
           nrow(white(men(lgbt(x)))),
           nrow(poc(men(straight(x)))),
           nrow(poc(men(lgbt(x)))),
           nrow(white(women(straight(x)))),
           nrow(white(women(lgbt(x)))),
           nrow(poc(women(straight(x)))),
           nrow(poc(women(lgbt(x)))))
  return(as_tibble(data.frame(dem,rep,ind,oth,obs)))
}
##Creating CSV of Results

party_results_table <- data.frame(group,
                                 party_analysis(nep_full,2000),
                                 party_analysis(nep_full,2004),
                                 party_analysis(nep_full,2006),
                                 party_analysis(nep_full,2008),
                                 party_analysis(nep_full,2010),
                                 party_analysis(nep_full,2012),
                                 party_analysis(nep_full,2014),
                                 party_analysis(nep_full,2016),
                                 party_analysis(nep_full,2018))
write.table(party_results_table, file="party_results_table.csv", sep=",",row.name=FALSE)

