## Presidential Analysis
percent_pres <- function(data_set){
  return(round(prop.table(table(data_set$PRES)),3))
}

pres_analysis <- function(data_set,target_year){
  x <- year(drop_na(data_set,PRES),target_year)
  no_vote <- c(percent_pres(straight(x))["0"],
               percent_pres(lgbt(x))["0"],
               percent_pres(men(straight(x)))["0"],
               percent_pres(men(lgbt(x)))["0"],
               percent_pres(women(straight(x)))["0"],
               percent_pres(women(lgbt(x)))["0"],
               percent_pres(white(straight(x)))["0"],
               percent_pres(white(lgbt(x)))["0"],
               percent_pres(poc(straight(x)))["0"],
               percent_pres(poc(lgbt(x)))["0"],
               percent_pres(white(men((straight(x)))))["0"],
               percent_pres(white(men(lgbt(x))))["0"],
               percent_pres(poc(men(straight(x))))["0"],
               percent_pres(poc(men(lgbt(x))))["0"],
               percent_pres(white(women(straight(x))))["0"],
               percent_pres(white(women(lgbt(x))))["0"],
               percent_pres(poc(women(straight(x))))["0"],
               percent_pres(poc(women(lgbt(x))))["0"])
  dem <-c(percent_pres(straight(x))["1"],
          percent_pres(lgbt(x))["1"],
          percent_pres(men(straight(x)))["1"],
          percent_pres(men(lgbt(x)))["1"],
          percent_pres(women(straight(x)))["1"],
          percent_pres(women(lgbt(x)))["1"],
          percent_pres(white(straight(x)))["1"],
          percent_pres(white(lgbt(x)))["1"],
          percent_pres(poc(straight(x)))["1"],
          percent_pres(poc(lgbt(x)))["1"],
          percent_pres(white(men((straight(x)))))["1"],
          percent_pres(white(men(lgbt(x))))["1"],
          percent_pres(poc(men(straight(x))))["1"],
          percent_pres(poc(men(lgbt(x))))["1"],
          percent_pres(white(women(straight(x))))["1"],
          percent_pres(white(women(lgbt(x))))["1"],
          percent_pres(poc(women(straight(x))))["1"],
          percent_pres(poc(women(lgbt(x))))["1"])
  rep <- c(percent_pres(straight(x))["2"],
           percent_pres(lgbt(x))["2"],
           percent_pres(men(straight(x)))["2"],
           percent_pres(men(lgbt(x)))["2"],
           percent_pres(women(straight(x)))["2"],
           percent_pres(women(lgbt(x)))["2"],
           percent_pres(white(straight(x)))["2"],
           percent_pres(white(lgbt(x)))["2"],
           percent_pres(poc(straight(x)))["2"],
           percent_pres(poc(lgbt(x)))["2"],
           percent_pres(white(men((straight(x)))))["2"],
           percent_pres(white(men(lgbt(x))))["2"],
           percent_pres(poc(men(straight(x))))["2"],
           percent_pres(poc(men(lgbt(x))))["2"],
           percent_pres(white(women(straight(x))))["2"],
           percent_pres(white(women(lgbt(x))))["2"],
           percent_pres(poc(women(straight(x))))["2"],
           percent_pres(poc(women(lgbt(x))))["2"])
  three <- c(percent_pres(straight(x))["3"],
           percent_pres(lgbt(x))["3"],
           percent_pres(men(straight(x)))["3"],
           percent_pres(men(lgbt(x)))["3"],
           percent_pres(women(straight(x)))["3"],
           percent_pres(women(lgbt(x)))["3"],
           percent_pres(white(straight(x)))["3"],
           percent_pres(white(lgbt(x)))["3"],
           percent_pres(poc(straight(x)))["3"],
           percent_pres(poc(lgbt(x)))["3"],
           percent_pres(white(men((straight(x)))))["3"],
           percent_pres(white(men(lgbt(x))))["3"],
           percent_pres(poc(men(straight(x))))["3"],
           percent_pres(poc(men(lgbt(x))))["3"],
           percent_pres(white(women(straight(x))))["3"],
           percent_pres(white(women(lgbt(x))))["3"],
           percent_pres(poc(women(straight(x))))["3"],
           percent_pres(poc(women(lgbt(x))))["3"])
  four <- c(percent_pres(straight(x))["4"],
           percent_pres(lgbt(x))["4"],
           percent_pres(men(straight(x)))["4"],
           percent_pres(men(lgbt(x)))["4"],
           percent_pres(women(straight(x)))["4"],
           percent_pres(women(lgbt(x)))["4"],
           percent_pres(white(straight(x)))["4"],
           percent_pres(white(lgbt(x)))["4"],
           percent_pres(poc(straight(x)))["4"],
           percent_pres(poc(lgbt(x)))["4"],
           percent_pres(white(men((straight(x)))))["4"],
           percent_pres(white(men(lgbt(x))))["4"],
           percent_pres(poc(men(straight(x))))["4"],
           percent_pres(poc(men(lgbt(x))))["4"],
           percent_pres(white(women(straight(x))))["4"],
           percent_pres(white(women(lgbt(x))))["4"],
           percent_pres(poc(women(straight(x))))["4"],
           percent_pres(poc(women(lgbt(x))))["4"])
  oth <- c(percent_pres(straight(x))["9"],
           percent_pres(lgbt(x))["9"],
           percent_pres(men(straight(x)))["9"],
           percent_pres(men(lgbt(x)))["9"],
           percent_pres(women(straight(x)))["9"],
           percent_pres(women(lgbt(x)))["9"],
           percent_pres(white(straight(x)))["9"],
           percent_pres(white(lgbt(x)))["9"],
           percent_pres(poc(straight(x)))["9"],
           percent_pres(poc(lgbt(x)))["9"],
           percent_pres(white(men((straight(x)))))["9"],
           percent_pres(white(men(lgbt(x))))["9"],
           percent_pres(poc(men(straight(x))))["9"],
           percent_pres(poc(men(lgbt(x))))["9"],
           percent_pres(white(women(straight(x))))["9"],
           percent_pres(white(women(lgbt(x))))["9"],
           percent_pres(poc(women(straight(x))))["9"],
           percent_pres(poc(women(lgbt(x))))["9"])
  obs <- c(nrow(straight(x)),
           nrow(lgbt(x)),
           nrow(men(straight(x))),
           nrow(men(lgbt(x))),
           nrow(women(straight(x))),
           nrow(women(lgbt(x))),
           nrow(white(straight(x))),
           nrow(white(lgbt(x))),
           nrow(poc(straight(x))),
           nrow(poc(lgbt(x))),
           nrow(white(men((straight(x))))),
           nrow(white(men(lgbt(x)))),
           nrow(poc(men(straight(x)))),
           nrow(poc(men(lgbt(x)))),
           nrow(white(women(straight(x)))),
           nrow(white(women(lgbt(x)))),
           nrow(poc(women(straight(x)))),
           nrow(poc(women(lgbt(x)))))
  return(as_tibble(data.frame(no_vote,dem,rep,three,four,oth,obs)))
}
##Creating CSV of Results

pres_results_table <- data.frame(group,
                                  pres_analysis(nep_full,2000),
                                  pres_analysis(nep_full,2004),
                                  pres_analysis(nep_full,2008),
                                  pres_analysis(nep_full,2012),
                                  pres_analysis(nep_full,2016))
write.table(pres_results_table, file="pres_results_table.csv", sep=",",row.name=FALSE)

